# Generated by Django 3.1.6 on 2021-02-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttag',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ProjectPicture',
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
