# Generated by Django 3.1.6 on 2021-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
