# Generated by Django 3.1.6 on 2021-06-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210611_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_miniature',
            field=models.TextField(default=''),
        ),
    ]
