# Generated by Django 3.1.6 on 2021-06-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_main_miniature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='texh_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
