# Generated by Django 3.1.6 on 2021-02-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details',
            field=models.TextField(default=''),
        ),
    ]
