# Generated by Django 3.1.6 on 2021-06-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_texh_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='texh_body',
            new_name='tech_body',
        ),
    ]
