# Generated by Django 3.1.6 on 2021-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_category_projectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scaled',
            field=models.TextField(default=''),
        ),
    ]
