# Generated by Django 3.1.6 on 2021-07-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_scaled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('miniature', models.TextField(default='')),
                ('index', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
                ('small_desc', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('small_desc', models.TextField(default='')),
                ('big_desc', models.TextField(default='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubServiceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubServiceChapterContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('content', models.TextField(default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.chapter')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.subservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
