# Generated by Django 3.1.6 on 2021-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_chapter_service_subservice_subservicechaptercontent_subservicetechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservice',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
